### DISCUSSION TITLE
Basis-tokens

### DISCUSSION THREAD

**Discussion by jeffreylauwers** [nl-design-system/backlog#405] [Design token suggestions]
Met de [basis-tokens](https://www.nldesignsystem.nl/handboek/huisstijl/themas/start-thema/#basis-tokens) bieden we organisaties een 'basis-set' van Common tokens. Door organisatieoverstijgend uit dezelfde bron te werken, worden componenten eenvoudig uitwisselbaar tussen organisaties.

Omdat we verschillende huisstijlen willen ondersteunen, is de set bewust ruim opgezet. Het is makkelijker om ongebruikte tokens later te verwijderen dan telkens nieuwe toe te moeten voegen.

We hopen dat de basis-tokens voldoende mogelijkheden bieden voor jouw organisatie. Mis je design tokens op het Common niveau? Dan staat het je vrij om extra Common tokens toe te voegen. Voorzie deze dan van de prefix van jouw organisatie.

Vragen of suggesties voor aanvullingen aan de basis-set kun je hier delen.

**Comment by sergei-maertens** [comment]
Zijn er richtlijnen voor ontwikkelaars van applicaties over wanneer ze welke tokens dienen te gebruiken, eventueel als fallback? Wat is de gewesnte opbouw van de CSS?

```css
.my-component {
    color: var(--my-component-color, var(--basis-color-action-1-color));
}
```

of

```css
.my-theme {
  --my-component-color: var(--basis-color-action-1-color);
}

.my-component {
    color: var(--my-component-color);
}
``` 

De tweede vorm heeft mijn voorkeur, want als applicatie-ontwikkelaar continue wijzigingen bijhouden in de basistokens van het startthema lijkt me onhoudbaar en niet-welkome overhead.
