### ISSUE TITLE
Component: strong emphasis component

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#138]
The strong emphasis component, like the HTML element `strong`.

## Design tokens

With the advent of [variable fonts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide), it would be nice to be able to specify the `font-weight` with a common font-weight design token, instead of relying on the default `font-weight: bold`. If the desired font-weight is for example 375, it would be nice to be able to do this:

```css
:root {
  --brand-typography-bold-font-weight: 375;
}

strong {
  font-weight: var(--brand-typography-bold-font-weight, bold);
}
```
